2025-03-19 19:30:13,941 INFO    MainThread:14084 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-19 19:30:13,941 INFO    MainThread:14084 [wandb_setup.py:_flush():67] Configure stats pid to 14084
2025-03-19 19:30:13,941 INFO    MainThread:14084 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Colton\.config\wandb\settings
2025-03-19 19:30:13,941 INFO    MainThread:14084 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Colton\Documents\GitHub\cs260r-assignment-2025winter\mini_project\wandb\settings
2025-03-19 19:30:13,941 INFO    MainThread:14084 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-19 19:30:13,942 INFO    MainThread:14084 [wandb_init.py:setup_run_log_directory():647] Logging user logs to runs\ppo_metadrive_final_testing\ppo_metadrive_final_testing_2025-03-19_19-30-02_afc450a1\wandb\run-20250319_193013-ppo_metadrive_final_testing_2025-03-19_19-30-02_afc450a1\logs\debug.log
2025-03-19 19:30:13,942 INFO    MainThread:14084 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to runs\ppo_metadrive_final_testing\ppo_metadrive_final_testing_2025-03-19_19-30-02_afc450a1\wandb\run-20250319_193013-ppo_metadrive_final_testing_2025-03-19_19-30-02_afc450a1\logs\debug-internal.log
2025-03-19 19:30:13,942 INFO    MainThread:14084 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001AB00EFBD90>
2025-03-19 19:30:13,945 INFO    MainThread:14084 [wandb_init.py:init():761] calling init triggers
2025-03-19 19:30:13,945 INFO    MainThread:14084 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-19 19:30:13,946 INFO    MainThread:14084 [wandb_init.py:init():784] starting backend
2025-03-19 19:30:13,946 INFO    MainThread:14084 [wandb_init.py:init():788] sending inform_init request
2025-03-19 19:30:13,960 INFO    MainThread:14084 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-19 19:30:13,960 INFO    MainThread:14084 [wandb_init.py:init():798] backend started and connected
2025-03-19 19:30:13,961 INFO    MainThread:14084 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-19 19:30:13,962 INFO    MainThread:14084 [wandb_init.py:init():891] updated telemetry
2025-03-19 19:30:14,227 INFO    MainThread:14084 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-19 19:30:14,583 INFO    MainThread:14084 [wandb_init.py:init():990] starting run threads in backend
2025-03-19 19:30:14,822 INFO    MainThread:14084 [wandb_run.py:_console_start():2375] atexit reg
2025-03-19 19:30:14,822 INFO    MainThread:14084 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-19 19:30:14,822 INFO    MainThread:14084 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-19 19:30:14,822 INFO    MainThread:14084 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-19 19:30:14,824 INFO    MainThread:14084 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-19 19:30:14,825 INFO    MainThread:14084 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-19 19:30:14,825 INFO    MainThread:14084 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-19 19:30:14,831 INFO    MainThread:14084 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-19 19:30:16,063 INFO    MainThread:14084 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-19 19:30:16,063 INFO    MainThread:14084 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-19 19:30:16,070 INFO    MainThread:14084 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-19 19:30:16,071 INFO    MainThread:14084 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-19 19:30:16,071 INFO    MainThread:14084 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-19 19:30:16,076 INFO    MainThread:14084 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-19 19:30:16,540 INFO    MainThread:14084 [wandb_run.py:_tensorboard_callback():1449] tensorboard callback: runs\ppo_metadrive_final_testing\ppo_metadrive_final_testing_2025-03-19_19-30-02_afc450a1\ppo_metadrive_final_testing_1, True
2025-03-19 19:30:16,546 INFO    MainThread:14084 [wandb_run.py:_config_callback():1261] config_cb None None {'algo': 'PPO', 'policy_class': "<class 'stable_baselines3.common.policies.ActorCriticPolicy'>", 'device': 'cpu', 'verbose': 2, 'policy_kwargs': '{}', 'num_timesteps': 0, '_total_timesteps': 1000000, '_num_timesteps_at_start': 0, 'seed': 'None', 'action_noise': 'None', 'start_time': 1742437816077597600, 'learning_rate': 5e-05, 'tensorboard_log': 'runs\\ppo_metadrive_final_testing\\ppo_metadrive_final_testing_2025-03-19_19-30-02_afc450a1', '_last_obs': '[[0.4861111  0.09722222 0.5        ... 1.         1.         1.        ]\n [0.4861111  0.09722222 0.5        ... 1.         1.         1.        ]\n [0.09722222 0.4861111  0.5        ... 1.         1.         1.        ]\n ...\n [0.09722222 0.4861111  0.5        ... 1.         1.         1.        ]\n [0.29166666 0.29166666 0.5        ... 1.         1.         1.        ]\n [0.09722222 0.4861111  0.5        ... 0.8566407  1.         1.        ]]', '_last_episode_starts': '[ True  True  True  True  True  True  True  True  True  True]', '_last_original_obs': 'None', '_episode_num': 0, 'use_sde': 'False', 'sde_sample_freq': -1, '_current_progress_remaining': 1.0, '_stats_window_size': 100, 'ep_info_buffer': 'deque([], maxlen=100)', 'ep_success_buffer': 'deque([], maxlen=100)', '_n_updates': 0, '_custom_logger': 'False', 'env': '<stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x000001AB7FE2B090>', '_vec_normalize_env': 'None', 'observation_space': 'Box(-0.0, 1.0, (259,), float32)', 'action_space': 'Box(-1.0, 1.0, (2,), float32)', 'n_envs': 10, 'n_steps': 256, 'gamma': 0.99, 'gae_lambda': 0.99, 'ent_coef': 0.0, 'vf_coef': 0.5, 'max_grad_norm': 10.0, 'rollout_buffer_class': "<class 'stable_baselines3.common.buffers.RolloutBuffer'>", 'rollout_buffer_kwargs': '{}', 'batch_size': 256, 'n_epochs': 20, 'clip_range': '<function get_schedule_fn.<locals>.<lambda> at 0x000001AB04375120>', 'clip_range_vf': 'None', 'normalize_advantage': 'True', 'target_kl': 'None', 'lr_schedule': '<function get_schedule_fn.<locals>.<lambda> at 0x000001AB00F5B060>', 'rollout_buffer': '<stable_baselines3.common.buffers.RolloutBuffer object at 0x000001AB00F00910>', 'policy': 'ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=259, out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0): Linear(in_features=259, out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64, out_features=2, bias=True)\n  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)', '_logger': '<stable_baselines3.common.logger.Logger object at 0x000001AB0165DB50>'}
2025-03-19 19:41:39,362 WARNING MsgRouterThr:14084 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\Colton\anaconda3\envs\cs260r\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Colton\anaconda3\envs\cs260r\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Colton\anaconda3\envs\cs260r\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Colton\anaconda3\envs\cs260r\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Colton\anaconda3\envs\cs260r\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Colton\anaconda3\envs\cs260r\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-19 19:41:39,745 INFO    MsgRouterThr:14084 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-19 19:41:39,745 INFO    MainThread:14084 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-19 19:41:39,745 INFO    MainThread:14084 [wandb_init.py:_pause_backend():564] pausing backend
